### ISSUE TITLE
CDATA markers not handled

### ISSUE THREAD

**Issue by madscientist159** [mwood77/pf2opn#20]
Older versions of pfSense tend to wrap all user strings in CDATA markers, as follows:
```
      <descr>
        <![CDATA[User provided text goes here]]>
      </descr>
```

OPNsense doesn't know what to do with these and inserts a bunch of unwanted newlines and spaces around the user text on restore.

**Comment by mwood77** [comment]
Should the CDATA fields be handled like this?

```xml
# before

<descr>
      <![CDATA[User provided text goes here]]>
</descr>
```

```xml
# after

<descr>
      User provided text goes here
</descr>
```

**Comment by mwood77** [comment]
CDATA tags have now been removed, and I've added the option to download a configuration with "no formatting." When it comes to recursive string interpolation, I don't see myself getting to that anytime in the near future.

Id be surprised if opnsense cannot handle either type of import, as both are valid XML.
